### ISSUE TITLE
Nerf rockets

### ISSUE THREAD

**Issue by NoahTheLegend** [Gingerbeard5773/Shiprekt#109]
Remove gaining shitton of money from hitting armor, nerf damage + optionally nerf fire rate
also would be good to change their hp or modify mgs to break it as it was long ago(?)

**Comment by Gingerbeard5773** [comment]
Done in commit 29e180a64088ef879a8d31d7c4da00df3356d8e2. Closing for now. May re-open if the changes did not prove to be successful
