### ISSUE TITLE
Couplings attach to enemy ships

### ISSUE THREAD

**Issue by Gingerbeard5773** [Gingerbeard5773/Shiprekt#114]
Currently, enemies cannot use couplings in any circumstance to 'dock' with your own ship. If they could in certain cases, it may be interesting for gameplay- such as instances of boarding an enemy's ship to fight hand to hand.

**Comment by NoahTheLegend** [comment]
Also remove breaking these couplings by enemy captain

**Comment by Gingerbeard5773** [comment]
Miniships will be able to dock with enemy motherships.

> Also remove breaking these couplings by enemy captain w spacebar
make a different issue for this one pls if you really think this is a big enough problem
