### ISSUE TITLE
Make harvester give only 75-85% (maybe randomly?) coins

### ISSUE THREAD

**Issue by NoahTheLegend** [Gingerbeard5773/Shiprekt#122]
Because it harvests much faster and can be operated from seat. Also you can choose now put harvesters at the match beginning, or not

**Comment by Gingerbeard5773** [comment]
Harvester does seem strong in some aspects. If I recall, the harvester had been tweaked a bit from Daskew to make it over powered so all the debris from a match would get cleaned up by players in game. I will look into the harvester and see if it can use any changes (which is highly likely)

**Comment by Gingerbeard5773** [comment]
done some changes
