### ISSUE TITLE
Special mark of true main ship while there are fake cores exist

### ISSUE THREAD

**Issue by NoahTheLegend** [Gingerbeard5773/Shiprekt#123]
for their team

**Comment by Gingerbeard5773** [comment]
Real mothership ship already does have a mark despite active decoys! The point of it is to be stealthy, a special mark would just undermine that reason?

**Comment by NoahTheLegend** [comment]
stealthy for enemies. If i put decoys, my team's true mothership becomes secondary. Annoying sometimes, inclusing full transforming of starter-box. A special mark like "gold-ringed" colored dot or smth, to see where the real yours mothership while there are more than 1 decoy cores. Thats just not intuitive until you respawn on it

**Comment by Gingerbeard5773** [comment]
So for the enemies it would be the same as it is now, but for team-mates it would show explicitly where the mothership really is? i approve, that would be more intuitive as you said

**Comment by NoahTheLegend** [comment]
yes, it is

**Comment by Gingerbeard5773** [comment]
done
