### ISSUE TITLE
Bullet collision deflection

### ISSUE THREAD

**Issue by NoahTheLegend** [Gingerbeard5773/Shiprekt#124]

**Comment by Gingerbeard5773** [comment]
This is actually a bug that I accidentally introduced early into my dev. I left it in because it is fun sometimes, I wont lie. If you or someone else believe that it is an annoyance ill go ahead and patch it up.

**Comment by NoahTheLegend** [comment]
i meant not lose speed when colliding with each other but change its trajectory. On collide it loses a lot of their speed but keep moving to diff sides. You misunderstood me in a *remove their collisions with each other* way

**Comment by Gingerbeard5773** [comment]
If thats the case then there would probably have to be some actual implementation to calculate where the bullets would go, since kag collisions don't keep a blobs velocity and it can stop both blobs if they hit directly. Is this worth it?

**Comment by NoahTheLegend** [comment]
idk how easy to do that calculations but if i believe if you put saving-the-bullet-velocity-code after it calculates the side to go after a collision then its worth and not that hard

**Comment by Gingerbeard5773** [comment]
calculations were unneeded, instead I changed the shape of the bullet to a triangle, with the point going in the direction it is shot, deflection is almost certain. this is done
