### ISSUE TITLE
New weapons question

### ISSUE THREAD

**Issue by NoahTheLegend** [Gingerbeard5773/Shiprekt#126]
If mortar doesnt fit into shiprekt, could you tell if there is going to happen or at least a chance to happen that some new weapon get introduced for crew teamwork and more various ways to break enemy ships? More mechanics or modifying existing weapons, maybe.
I believe mg\cannon\missile launcher shouldnt be the only weapons and adding new may improve the game balance and experience. 

I'll send some ideas as separated and simplified issues, if you like anything, im always down to go coding that.

**Comment by Gingerbeard5773** [comment]
The focus is on unique blocks that have interactions with other blocks in interesting ways.
