### ISSUE TITLE
Manually operated machinegun

### ISSUE THREAD

**Issue by slava998** [Gingerbeard5773/Shiprekt#158]
it would be great to have one so that the ship's crew could have a larger role and to defeat small ships and players

**Comment by Gingerbeard5773** [comment]
This idea was stated in #132 . This may be an idea worthy looking into with conjunction of #145

**Comment by Gingerbeard5773** [comment]
I need someone to sprite this and it will be implemented

**Comment by Gingerbeard5773** [comment]
implemented
