### ISSUE TITLE
Huge spectator zoom-out

### ISSUE THREAD

**Issue by ProfessorFumbleFingers** [Gingerbeard5773/Shiprekt#36]
It would be interesting to be able to watch battles unfold from an extreme zoom-out.

I've been told this isn't doable by some, and it is doable by others.

The detail doesn't need to be brilliant, a somewhat sketchy look from a huge perspective would be better than nothing.

**Comment by Gingerbeard5773** [comment]
done! cool suggestion, also added in the ability to follow ships by clicking on them
