### ISSUE TITLE
Hyperflak changes

### ISSUE THREAD

**Issue by ProfessorFumbleFingers** [Gingerbeard5773/Shiprekt#46]
I like hyperflak but I feel dissatified when using it. Currently it does a heap of damage (which is good), but has an extremely large blast area, easily hitting ships in most situations. I think this is a missed opportunity to have a fun weapon where hitting the enemy ship is a challenge and if done very rewarding with a huge punch.

**Changes:**

- Can only hit one block with full damage or two blocks with half damage (depending on where it hits)
- Has different projectile hit animation, one that reflects a more concentrated narrower attack 
- New projectile hit sound
- Projectile does not stop around where mouse is clicked; it continues to full range and drops into water if miss (similar to ap cannon)
- New sprite for weapon (to differentiate it from flak cannon)

-I want to reinvent this thing fresh, fine and fierce.

**Comment by Gingerbeard5773** [comment]
gonna remove hyperflak LOL
