### ISSUE TITLE
Lower blocks' cost (and maybe weight)

### ISSUE THREAD

**Issue by NoahTheLegend** [Gingerbeard5773/Shiprekt#50]
I think cheap blocks are best way to stay against agressive meta and makes game more separated from economic state of the team.
Plus you wont _go far_ being covered in armor so it would make game more friendly to different ships in meta and blocks could be used more often

**Comment by NoahTheLegend** [comment]
made a pr for this (also nerfed ram engines cost

**Comment by Gingerbeard5773** [comment]
Compromised and made it so blocks are only cheaper during warm-up, and original costs come back during game-time. Follow-up changes are likely. 
Expect more on the topic of weight.
