### ISSUE TITLE
Add electric system for ram engines and some other stuff like lasers and destructors

### ISSUE THREAD

**Issue by NoahTheLegend** [Gingerbeard5773/Shiprekt#51]
Could be a better way to nerf ram engines than decreasing its statistics.
Plus new gameplay advantages: covering energy system with armor and focusing on it (there is no many targets to focus now xd)
Plus new blocks like **auto-repairing near blocks system**, **money-point on your ship** and **electric floor** that damages enemies who stand on it.

If electricity usage is bigger than generators' production, then efficiency of some of this becomes worse or even disables until usage < productivity

**Comment by NoahTheLegend** [comment]
Also you may add batteries (energy storages)

**Comment by Gingerbeard5773** [comment]
Two issues for same thing, closing
