### ISSUE TITLE
New blocks and electricity changes

### ISSUE THREAD

**Issue by NoahTheLegend** [Gingerbeard5773/Shiprekt#52]
So i was thinking about electro-system for gameplay, when you can produce, store and use electricity on your ship.
The point of working is: generators produce energy, then this energy comes to ship's core, and being storaged there. Optionally needs a limiter. Some stuff that is using energy

Add electric floor that damages people periodically, who stands on it. Needs electricity system on ship which contains this block.
Add a passive block (solid) that repairs near blocks in 3x3 or 5x5 zone. Depends on its efficiency and stats. Needs energy
Add money-point, passively produces money for team. Needs energy
Add two types of generators: light and armored with same production speed (maybe) and different weight\hp
Light generator: low hp, light weight, explodes on death like a regular bomb or twice weaker.
Armored generator: explodes w 25% of a regular bomb power

Rework lasers (point defense) should require energy
Rework ram engines should require energy
Rework pulsors (if they will become multiused): should require energy (note: as a balanced solution for its endless work)

**Comment by Gingerbeard5773** [comment]
Sounds like an entirely different mod. As of the moment an electricity system would only hinder gameplay. Though a cool concept that has been discussed in past mods I believe it is unfit for shiprekt. Closing
