### ISSUE TITLE
Add sails and wind

### ISSUE THREAD

**Issue by NoahTheLegend** [Gingerbeard5773/Shiprekt#53]
Suggestion in header

**Comment by Gingerbeard5773** [comment]
Sails not really worth doing, not really sure how to even go about it either. On the other end though, wind has been discussed before as part of possible ambience additions. I can see it clearly. If it was given mechanical use it might be annoying though

**Comment by Gingerbeard5773** [comment]
Closing and putting into ambience sounds #81
