### ISSUE TITLE
Lower each weapon's ammo capacity or firing time

### ISSUE THREAD

**Issue by NoahTheLegend** [Gingerbeard5773/Shiprekt#54]
Also add a merch-block that offers different types of ammo. Each of that should be stored to ship's core or weapons manually. 
For all this people need inventory to have limited ammo-carrying

Plus after this improvement\change separated ships with weapons will become addicted to mothership for auto-restock ammo

**Comment by Gingerbeard5773** [comment]
Merch-block & new inventory aren't worth doing. Changing this issue's purpose into a nerf for weapon ammo/firing time

**Comment by Gingerbeard5773** [comment]
Done in previous commits
