### ISSUE TITLE
Add a colourful and bright splash-textline

### ISSUE THREAD

**Issue by NoahTheLegend** [Gingerbeard5773/Shiprekt#57]
that says you can share money between team as captain or send money to captain
optionally: that says you can also disband your ship and refuse being captain (never used and barely useful tho)

**Comment by NoahTheLegend** [comment]
during warm-up(?)

**Comment by NoahTheLegend** [comment]
made a pr for this

**Comment by Gingerbeard5773** [comment]
Improved it on the F1 menu rather than being visible constantly.
