### ISSUE TITLE
Banning\kicking as a result of a crash

### ISSUE THREAD

**Issue by NoahTheLegend** [Gingerbeard5773/Shiprekt#60]
server dies after a kick or a ban

**Comment by Gingerbeard5773** [comment]
Tested with bots, no crash.

**Comment by Gingerbeard5773** [comment]
Doesn't happen on Zable's server. Closing

**Comment by Gingerbeard5773** [comment]
Happens on vamist's server, reopening until we figure it out.

**Comment by Gingerbeard5773** [comment]
Fixed with commit https://github.com/Gingerbeard5773/Shiprekt/commit/4b2a01d6100ab608085210914f452eb94832e5a1
One less crash!
