### ISSUE TITLE
Missing damage frames

### ISSUE THREAD

**Issue by Gingerbeard5773** [Gingerbeard5773/Shiprekt#87]
Blocks such as platforms or ram-engines don't have damage frames, when they should. Just need a spriter to work on these and then we can add it in for the blocks.

**Comment by Gingerbeard5773** [comment]
If someone is willing to sprite, this can be done

**Comment by NoahTheLegend** [comment]
Do you need just a ram damage particles sprite sheet?

**Comment by Gingerbeard5773** [comment]
referring to extra frames when the block is damaged like the wooden hull

**Comment by Gingerbeard5773** [comment]
done
